// server.js
const express = require("express");
const cors = require("cors");

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors({ origin: "*" }));


const doctorsData = [
  {
    id: 1,
    name: "Dr. Aarav Patel",
    expertise: "Cardiology",
    city: "Mumbai",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Patel",
  },
  {
    id: 2,
    name: "Dr. Zara Khan",
    expertise: "Orthopedics",
    city: "Delhi",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Zara+Khan",
  },
  {
    id: 3,
    name: "Dr. Advait Sharma",
    expertise: "Dermatology",
    city: "Bangalore",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Advait+Sharma",
  },
  {
    id: 4,
    name: "Dr. Nia Gupta",
    expertise: "Pediatrics",
    city: "Kolkata",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Nia+Gupta",
  },
  {
    id: 5,
    name: "Dr. Arjun Singh",
    expertise: "Ophthalmology",
    city: "Chennai",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Singh",
  },
  {
    id: 6,
    name: "Dr. Ava Verma",
    expertise: "Gynecology",
    city: "Hyderabad",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Ava+Verma",
  },
  {
    id: 7,
    name: "Dr. Vihaan Joshi",
    expertise: "ENT",
    city: "Ahmedabad",
    sex: "male",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Vihaan+Joshi",
  },
  {
    id: 8,
    name: "Dr. Siya Mehra",
    expertise: "Dentistry",
    city: "Pune",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Siya+Mehra",
  },
  {
    id: 9,
    name: "Dr. Aryan Khanna",
    expertise: "Psychiatry",
    city: "Jaipur",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aryan+Khanna",
  },
  {
    id: 10,
    name: "Dr. Ananya Singh",
    expertise: "Endocrinology",
    city: "Lucknow",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Ananya+Singh",
  },
  {
    id: 11,
    name: "Dr. Arnav Agarwal",
    expertise: "Urology",
    city: "Nagpur",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Arnav+Agarwal",
  },
  {
    id: 12,
    name: "Dr. Riya Mehta",
    expertise: "Dermatology",
    city: "Patna",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Riya+Mehta",
  },
  {
    id: 13,
    name: "Dr. Yuvraj Malhotra",
    expertise: "Cardiac Surgery",
    city: "Surat",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Yuvraj+Malhotra",
  },
  {
    id: 14,
    name: "Dr. Saanvi Reddy",
    expertise: "Neurology",
    city: "Indore",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Saanvi+Reddy",
  },
  {
    id: 15,
    name: "Dr. Arush Saxena",
    expertise: "Gastroenterology",
    city: "Bhopal",
    sex: "male",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Arush+Saxena",
  },
  {
    id: 16,
    name: "Dr. Aanya Sharma",
    expertise: "Oncology",
    city: "Chandigarh",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Aanya+Sharma",
  },
  {
    id: 17,
    name: "Dr. Aadi Joshi",
    expertise: "Dentistry",
    city: "Nashik",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aadi+Joshi",
  },
  {
    id: 18,
    name: "Dr. Anika Kapoor",
    expertise: "Psychiatry",
    city: "Ludhiana",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Anika+Kapoor",
  },
  {
    id: 19,
    name: "Dr. Aarush Singh",
    expertise: "Orthopedics",
    city: "Amritsar",
    sex: "male",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Aarush+Singh",
  },
  {
    id: 20,
    name: "Dr. Kyra Sharma",
    expertise: "Dermatology",
    city: "Agra",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Kyra+Sharma",
  },
  {
    id: 21,
    name: "Dr. Advaita Reddy",
    expertise: "Cardiology",
    city: "Varanasi",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Reddy",
  },
  {
    id: 22,
    name: "Dr. Kabir Kapoor",
    expertise: "Ophthalmology",
    city: "Srinagar",
    sex: "male",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Kabir+Kapoor",
  },
  {
    id: 23,
    name: "Dr. Ava Agarwal",
    expertise: "Gynecology",
    city: "Jodhpur",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Ava+Agarwal",
  },
  {
    id: 24,
    name: "Dr. Aryan Choudhary",
    expertise: "ENT",
    city: "Raipur",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aryan+Choudhary",
  },
  {
    id: 25,
    name: "Dr. Saira Nair",
    expertise: "Dermatology",
    city: "Gwalior",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Saira+Nair",
  },
  {
    id: 26,
    name: "Dr. Aarav Mehra",
    expertise: "Pediatrics",
    city: "Kota",
    sex: "male",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Aarav+Mehra",
  },
  {
    id: 27,
    name: "Dr. Aanya Verma",
    expertise: "Oncology",
    city: "Guwahati",
    sex: "female",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Aanya+Verma",
  },
  {
    id: 28,
    name: "Dr. Arjun Yadav",
    expertise: "Urology",
    city: "Kochi",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Yadav",
  },
  {
    id: 29,
    name: "Dr. Saanvi Menon",
    expertise: "Cardiology",
    city: "Thiruvananthapuram",
    sex: "female",
    image: "https://dummyimage.com/150x150/2ecc71/ffffff&text=Dr.+Saanvi+Menon",
  },
  {
    id: 30,
    name: "Dr. Kabir Iyer",
    expertise: "Gastroenterology",
    city: "Coimbatore",
    sex: "male",
    image: "https://dummyimage.com/150x150/e74c3c/ffffff&text=Dr.+Kabir+Iyer",
  },
  {
    id: 31,
    name: "Dr. Anika Nair",
    expertise: "Orthopedics",
    city: "Madurai",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anika+Nair",
  },
  {
    id: 32,
    name: "Dr. Zara Menon",
    expertise: "Dentistry",
    city: "Tiruchirappalli",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Zara+Menon",
  },
  {
    id: 33,
    name: "Dr. Arnav Iyer",
    expertise: "Neurology",
    city: "Salem",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arnav+Iyer",
  },
  {
    id: 34,
    name: "Dr. Anaya Agarwal",
    expertise: "Psychiatry",
    city: "Vijayawada",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anaya+Agarwal",
  },
  {
    id: 35,
    name: "Dr. Aarush Menon",
    expertise: "Ophthalmology",
    city: "Visakhapatnam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Menon",
  },
  {
    id: 36,
    name: "Dr. Aanya Reddy",
    expertise: "Gynecology",
    city: "Guntur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Reddy",
  },
  {
    id: 37,
    name: "Dr. Advaita Kapoor",
    expertise: "ENT",
    city: "Nellore",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Kapoor",
  },
  {
    id: 38,
    name: "Dr. Anaya Iyer",
    expertise: "Cardiology",
    city: "Kurnool",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anaya+Iyer",
  },
  {
    id: 39,
    name: "Dr. Aarush Menon",
    expertise: "Orthopedics",
    city: "Rajahmundry",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Menon",
  },
  {
    id: 40,
    name: "Dr. Arjun Choudhary",
    expertise: "Dermatology",
    city: "Tirupati",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Choudhary",
  },
  {
    id: 41,
    name: "Dr. Aanya Iyer",
    expertise: "Neurology",
    city: "Kakinada",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Iyer",
  },
  {
    id: 42,
    name: "Dr. Saanvi Yadav",
    expertise: "Gastroenterology",
    city: "Anantapur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
  {
    id: 43,
    name: "Dr. Kabir Iyer",
    expertise: "Oncology",
    city: "Kollam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Kabir+Iyer",
  },
  {
    id: 44,
    name: "Dr. Advait Menon",
    expertise: "Pediatrics",
    city: "Alappuzha",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advait+Menon",
  },
  {
    id: 45,
    name: "Dr. Aanya Nair",
    expertise: "Dentistry",
    city: "Thiruvalla",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Nair",
  },
  {
    id: 46,
    name: "Dr. Arush Iyer",
    expertise: "Urology",
    city: "Kottayam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arush+Iyer",
  },
  {
    id: 47,
    name: "Dr. Saanvi Yadav",
    expertise: "Psychiatry",
    city: "Pathanamthitta",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
  {
    id: 48,
    name: "Dr. Arjun Menon",
    expertise: "Cardiology",
    city: "Idukki",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Menon",
  },
  {
    id: 49,
    name: "Dr. Aarav Iyer",
    expertise: "Dermatology",
    city: "Ernakulam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Iyer",
  },
  {
    id: 50,
    name: "Dr. Saanvi Yadav",
    expertise: "Orthopedics",
    city: "Malappuram",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
  {
    id: 51,
    name: "Dr. Advaita Reddy",
    expertise: "Cardiology",
    city: "Mumbai",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Reddy",
  },
  {
    id: 52,
    name: "Dr. Siya Kapoor",
    expertise: "Orthopedics",
    city: "Delhi",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Siya+Kapoor",
  },
  {
    id: 53,
    name: "Dr. Aarav Agarwal",
    expertise: "Dermatology",
    city: "Bangalore",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Agarwal",
  },
  {
    id: 54,
    name: "Dr. Zara Choudhary",
    expertise: "Pediatrics",
    city: "Kolkata",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Zara+Choudhary",
  },
  {
    id: 55,
    name: "Dr. Aarush Menon",
    expertise: "Ophthalmology",
    city: "Chennai",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Menon",
  },
  {
    id: 56,
    name: "Dr. Advaita Iyer",
    expertise: "Gynecology",
    city: "Hyderabad",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Iyer",
  },
  {
    id: 57,
    name: "Dr. Aanya Joshi",
    expertise: "ENT",
    city: "Ahmedabad",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Joshi",
  },
  {
    id: 58,
    name: "Dr. Arjun Agarwal",
    expertise: "Dentistry",
    city: "Pune",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Agarwal",
  },
  {
    id: 59,
    name: "Dr. Anaya Sharma",
    expertise: "Psychiatry",
    city: "Jaipur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anaya+Sharma",
  },
  {
    id: 60,
    name: "Dr. Kabir Yadav",
    expertise: "Endocrinology",
    city: "Lucknow",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Kabir+Yadav",
  },
  {
    id: 61,
    name: "Dr. Saanvi Choudhary",
    expertise: "Urology",
    city: "Nagpur",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Choudhary",
  },
  {
    id: 62,
    name: "Dr. Zara Verma",
    expertise: "Dermatology",
    city: "Patna",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Zara+Verma",
  },
  {
    id: 63,
    name: "Dr. Aarush Agarwal",
    expertise: "Cardiac Surgery",
    city: "Surat",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Agarwal",
  },
  {
    id: 64,
    name: "Dr. Siya Iyer",
    expertise: "Neurology",
    city: "Indore",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Siya+Iyer",
  },
  {
    id: 65,
    name: "Dr. Aanya Kapoor",
    expertise: "Gastroenterology",
    city: "Bhopal",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Kapoor",
  },
  {
    id: 66,
    name: "Dr. Advaita Nair",
    expertise: "Oncology",
    city: "Chandigarh",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Nair",
  },
  {
    id: 67,
    name: "Dr. Anika Menon",
    expertise: "Dentistry",
    city: "Nashik",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anika+Menon",
  },
  {
    id: 68,
    name: "Dr. Aarav Yadav",
    expertise: "Psychiatry",
    city: "Ludhiana",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Yadav",
  },
  {
    id: 69,
    name: "Dr. Saanvi Joshi",
    expertise: "Orthopedics",
    city: "Amritsar",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Joshi",
  },
  {
    id: 70,
    name: "Dr. Aanya Verma",
    expertise: "Dermatology",
    city: "Agra",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Verma",
  },
  {
    id: 71,
    name: "Dr. Advaita Reddy",
    expertise: "Cardiology",
    city: "Varanasi",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Reddy",
  },
  {
    id: 72,
    name: "Dr. Kabir Kapoor",
    expertise: "Ophthalmology",
    city: "Srinagar",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Kabir+Kapoor",
  },
  {
    id: 73,
    name: "Dr. Ava Agarwal",
    expertise: "Gynecology",
    city: "Jodhpur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Ava+Agarwal",
  },
  {
    id: 74,
    name: "Dr. Aryan Choudhary",
    expertise: "ENT",
    city: "Raipur",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aryan+Choudhary",
  },
  {
    id: 75,
    name: "Dr. Siya Nair",
    expertise: "Dermatology",
    city: "Gwalior",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Siya+Nair",
  },
  {
    id: 76,
    name: "Dr. Aarav Mehra",
    expertise: "Pediatrics",
    city: "Kota",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Mehra",
  },
  {
    id: 77,
    name: "Dr. Aanya Verma",
    expertise: "Oncology",
    city: "Guwahati",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Verma",
  },
  {
    id: 78,
    name: "Dr. Arjun Yadav",
    expertise: "Urology",
    city: "Kochi",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Yadav",
  },
  {
    id: 79,
    name: "Dr. Saanvi Menon",
    expertise: "Cardiology",
    city: "Thiruvananthapuram",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Menon",
  },
  {
    id: 80,
    name: "Dr. Kabir Iyer",
    expertise: "Gastroenterology",
    city: "Coimbatore",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Kabir+Iyer",
  },
  {
    id: 81,
    name: "Dr. Anika Nair",
    expertise: "Orthopedics",
    city: "Madurai",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anika+Nair",
  },
  {
    id: 82,
    name: "Dr. Zara Menon",
    expertise: "Dentistry",
    city: "Tiruchirappalli",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Zara+Menon",
  },
  {
    id: 83,
    name: "Dr. Arnav Iyer",
    expertise: "Neurology",
    city: "Salem",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arnav+Iyer",
  },
  {
    id: 84,
    name: "Dr. Anaya Agarwal",
    expertise: "Psychiatry",
    city: "Vijayawada",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anaya+Agarwal",
  },
  {
    id: 85,
    name: "Dr. Aarush Menon",
    expertise: "Ophthalmology",
    city: "Visakhapatnam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Menon",
  },
  {
    id: 86,
    name: "Dr. Aanya Reddy",
    expertise: "Gynecology",
    city: "Guntur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Reddy",
  },
  {
    id: 87,
    name: "Dr. Advaita Kapoor",
    expertise: "ENT",
    city: "Nellore",
    sex: "female",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advaita+Kapoor",
  },
  {
    id: 88,
    name: "Dr. Anaya Iyer",
    expertise: "Cardiology",
    city: "Kurnool",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Anaya+Iyer",
  },
  {
    id: 89,
    name: "Dr. Aarush Menon",
    expertise: "Orthopedics",
    city: "Rajahmundry",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarush+Menon",
  },
  {
    id: 90,
    name: "Dr. Arjun Choudhary",
    expertise: "Dermatology",
    city: "Tirupati",
    sex: "male",
    image:
      "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Choudhary",
  },
  {
    id: 91,
    name: "Dr. Aanya Iyer",
    expertise: "Neurology",
    city: "Kakinada",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Iyer",
  },
  {
    id: 92,
    name: "Dr. Saanvi Yadav",
    expertise: "Gastroenterology",
    city: "Anantapur",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
  {
    id: 93,
    name: "Dr. Kabir Iyer",
    expertise: "Oncology",
    city: "Kollam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Kabir+Iyer",
  },
  {
    id: 94,
    name: "Dr. Advait Menon",
    expertise: "Pediatrics",
    city: "Alappuzha",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Advait+Menon",
  },
  {
    id: 95,
    name: "Dr. Aanya Nair",
    expertise: "Dentistry",
    city: "Thiruvalla",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aanya+Nair",
  },
  {
    id: 96,
    name: "Dr. Arush Iyer",
    expertise: "Urology",
    city: "Kottayam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arush+Iyer",
  },
  {
    id: 97,
    name: "Dr. Saanvi Yadav",
    expertise: "Psychiatry",
    city: "Pathanamthitta",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
  {
    id: 98,
    name: "Dr. Arjun Menon",
    expertise: "Cardiology",
    city: "Idukki",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Arjun+Menon",
  },
  {
    id: 99,
    name: "Dr. Aarav Iyer",
    expertise: "Dermatology",
    city: "Ernakulam",
    sex: "male",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Aarav+Iyer",
  },
  {
    id: 100,
    name: "Dr. Saanvi Yadav",
    expertise: "Orthopedics",
    city: "Malappuram",
    sex: "female",
    image: "https://dummyimage.com/150x150/3498db/ffffff&text=Dr.+Saanvi+Yadav",
  },
];

const patientFeedback = {
  patient_feedback: [
    {
      id: 1,
      name: "Alice",
      sex: "female",
      comment:
        "The fixed health online consultation was a game-changer for me. It was convenient, and I got prompt and reliable medical advice without leaving my home.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 2,
      name: "Bob",
      sex: "male",
      comment:
        "I was skeptical at first, but the fixed health online consultation exceeded my expectations. The doctors were knowledgeable, and I felt comfortable discussing my health concerns.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 3,
      name: "Charlie",
      sex: "female",
      comment:
        "I appreciate the ease of scheduling appointments and the thoroughness of the online consultations. It saved me time and hassle, and I received quality care.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 4,
      name: "Diana",
      sex: "female",
      comment:
        "The fixed health online consultation made healthcare accessible, especially during busy times. The doctors were attentive, and the platform was user-friendly.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 5,
      name: "Eva",
      sex: "female",
      comment:
        "As someone with a chronic condition, the online consultations provided me with the necessary support and guidance. It's a great option for ongoing healthcare management.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 6,
      name: "Frank",
      sex: "male",
      comment:
        "I was pleasantly surprised by the personalized care I received during the online consultation. The doctors took the time to understand my situation and provided tailored advice.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 7,
      name: "Grace",
      sex: "female",
      comment:
        "The fixed health online consultation was a lifeline during the pandemic. It allowed me to address health concerns without unnecessary exposure to crowded waiting rooms.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 8,
      name: "Harry",
      sex: "male",
      comment:
        "I appreciated the convenience of follow-up consultations through the online platform. It made managing my health conditions much more efficient.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 9,
      name: "Ivy",
      sex: "female",
      comment:
        "The online consultations were a time-saver for me. No more commuting or waiting – just quality healthcare from the comfort of my home.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
    {
      id: 10,
      name: "Jack",
      sex: "male",
      comment:
        "I initially hesitated, but the fixed health online consultation turned out to be a fantastic experience. The doctors were professional, and the process was seamless.",
      image_url:
        "https://unsplash.com/photos/shallow-focus-photography-of-woman-outdoor-during-day-rDEOVtE7vOs",
    },
  ],
};

app.get("/api/doctors", (req, res) => {
  const { city } = req.query;
  if (city) {
    const filteredDoctors = doctorsData.filter(
      (doctor) => doctor.city.toLowerCase() === city.toLowerCase()
    );
    res.json(filteredDoctors);
  } else {
    res.status(400).json({ error: "City parameter is required." });
  }
});

app.get("/api/patients", (req, res) => {
  res.json(patientFeedback);
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
